url: 
baseurl: 

# Site settings
title: Terraroma Ecuador
email: ventas@terraromaec.com
description: "Website"


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/terraromaec
  - title: instagram
    url: https://www.instagram.com/terraromaec/
  - title: tiktok
    url: http://twitter.com/terramoraec

# Postal address (add as many lines as necessary)
address:
  - line: Leonardo Murialdo E15-84 y Pedro Guerrero
  - line: Quito - Ecuador

# Build settings
markdown: kramdown
permalink: pretty
